// "use client"
import { Inter } from 'next/font/google';
import Script from 'next/script';
// import { createGlobalStyle } from "styled-components";
import ContextProvider from '../../components/ContextProvider';
import './globals.css';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// const GlobalStyles = createGlobalStyle`
// body{
//   padding : 0;

// }`

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       {/* <GlobalStyles/> */}

       <ContextProvider>{children}</ContextProvider>
       
       </body>
       <Script src="https://cdn.tailwindcss.com"></Script>
    </html>
  )
}
